baseURL = 'http://congee.gay/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '3.145926535'
theme = "hugo-vitae"
pagination = 10

[params]
avatar = "https://i.imgur.com/gzYsqae.png"
wordCount = true
tags = true
categories = true


[params.comments]
enabled = false

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Translations"
url = "/tags/translation/"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter"
url = "https://twitter.com/brainrotforever"

[[params.social]]
name = "Ao3"
icon = "fa-solid fa-book"
url = "https://archiveofourown.org/users/Congee/profile"

[[params.social]]
name = "Pixiv"
icon = "fa-solid fa-palette"
url = "https://www.pixiv.net/en/users/2315149"
