baseURL = 'http://congee.gay/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '3.145926535'
theme = "hugo-vitae"
pagination = 10

[params]
avatar = "https://i.imgur.com/gzYsqae.png"
wordCount = true
tags = true
categories = true


[params.comments]
enabled = false
