baseURL = 'http://congee.gay/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '3.145926535'
theme = "hugo-vitae"
pagination = 10

[params]
avatar = "https://i.imgur.com/85z2Tot.png"
wordCount = true

[params.comments]
enabled = false
