baseURL = 'http://congee.gay/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '3.145926535'
theme = "hugo-vitae"
pagination = 10

[params]
avatar = "https://i.imgur.com/gzYsqae.png"
wordCount = true
tags = true
categories = true


[params.comments]
enabled = false

# Navigation
[[menu.main]]
name = "Home"
url = "/https://congee.gay/"
weight = 1

[[menu.main]]
name = "Resources"
url = "/fanfiction-resources"
weight = 2

[[menu.main]]
name = "About"
url = "/aboutme"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5