baseURL = 'http://congee.gay/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '欲の袋に底なし'
theme = "hugo-vitae"
# pagination = 10

[params]
avatar = "https://i.imgur.com/hxT60XS.gif"
wordCount = true
tags = true
categories = true


[params.comments]
enabled = false

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Translations"
url = "/tags/translation/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Short Ship Fics"
url = "/tags/ship-fic"
weight = 4

# Social Menu
